#!/usr/local/cpanel/3rdparty/bin/perl

use strict;
use warnings;

use lib '/usr/local/cpanel';

use Cpanel::ChangePasswd (); # cPanel API Interna

# Global

my $longitudpw = 12; # longitud de la contrasena
my @caracterespw = ("a".."z","A".."Z","0".."9"); # caracteres a incluir en las contrasenas al azar

# Codigo principal

my ($user, $password) = @ARGV;

if ($user) {
    if ($user eq 'root') { # si eres root
        print "[-] ERROR! No podemos cambiar la contrasena root.\n";
    } else {
        unless ($password) { # si no nos dan una contrasena, inventamos una
            print "[+] No has promorcionado una contrasena, inventaremos una.\n";
            $password = randtext($longitudpw, @caracterespw);
        }
        
        
        my ($status, $msg) = Cpanel::ChangePasswd::change_password(user => $user, new_password => $password, optional_services => {mysql => 1});
        
        if ($status) {
        print "[+] Exito: $msg\n";
	print "[+] Procesando cambio de contrasena\n";
        print "[+] Usuario : $user\n";
        print "[+]  Clave  : $password\n\n";
        } else {
            print "[-] ERROR!: $msg\n";
        }
    }
} else {
    print "[-] ERROR! No has proporcionado un usuario valido.\n";
    uso();
}

exit;

# terminamos codigo principal

sub uso {
    print "[-] Uso: $0 usuario [contrasena]\n";
    print "[-] La contrasena se genera aleatoriamente si se omite.\n";
}

sub randtext {
    my $length = shift;
    return join("",@_[map{rand @_} (1..$length)]); 
}
